### ISSUE TITLE
UI Design improvements (Styles and Themes)

### ISSUE THREAD

**Issue by tsadarsh** [tsadarsh/Pymanujan#12]
# UI design overhaul
This issue calls for discussion and PRs for various design upgrades to PyClac Graphical User Interface. Feel free to post your work and ideas in this thread. 
Listed below are proposed areas for overhaul:
- - [ ] :art: Implementation of styles
- - [ ] :art: Additional color schemes
- - [ ] :building_construction: Button geometry
- - [ ] :sound: Sound feedback during UI interaction
- - [ ] :pen: Font styles

## Implementation of styles/Additional color schemes :art: 
PyCalc currently implements a standard theme in `default_style_settings`. New themes to be named as `<name_of_theme>_style_settings` under `class GUI`. Each widget's style can be chaged by calling `styler.configure`  method with following arguments:
```python
def newStyle_style_settings(self):
    self.styler.configure("TLabel",  [widget specific style settings...]) # for ttk.Label
    self.styler.configure("TButton",  [widget specific style settings...]) # for ttk.Button
    self.styler.configure("NewButton.TLabel",  [widget specific style settings...]) # style for specific button
```
Widget specific commands can be found [here](https://www.tcl.tk/man/tcl8.6/TkCmd/contents.htm).

## Button geometry :building_construction: 
Button geometry is a bit involved. Each widget in tkinter is made of many elements. For example possible button elements can be represented like this:

![Possible elements of Button](https://tkdocs.com/images/button_elements.png)

[TkDocs](https://tkdocs.com/tutorial/styles.html#insidestyle) is an excellent place to have your feet dipped into widget elements its layout.

## Sound feedback during UI interaction :sound: 
Currently PyCalc has no audio feedback during keypad and button interaction. This area is open for implemneation ideas and sound selection. 

## Font styles :pen: 
All the available font families in tkinter can be obtained from `font.families`. Refer [here](https://stackoverflow.com/a/39614028) for getting font families. 
Note: tkinter *named fonts* are platform specific.

**Comment by precious-omovoiye** [comment]
I will take this up

**Comment by maddypie** [comment]
@precious-omovoiye, I am assigning this to you. Do update us on this thread.

**Comment by precious-omovoiye** [comment]
Alright @maddypie, do you have any preference as regards the design?

**Comment by maddypie** [comment]
I would not prefer a UI with a lot of bright colours. Currently, "Equal-to" button is a good example of a bad colour choice. Talking about the layout, I think having a compact design is a better choice. Calculators are hardly made 'full-screen' by the users. 
I largely give you all the freedom to try out design patterns according to your taste. 
Please feel free to dress up 'PyCalc' in a variety of designs and themes.

**Comment by precious-omovoiye** [comment]
Design is ongoing already.

**Comment by maddypie** [comment]
@precious-omovoiye I hope you are doing good :smile: . 
I would love to know the progress. Is there any help  you need from my side?

**Comment by precious-omovoiye** [comment]
So sorry for the delay @maddypie, I got caught up in a situation over here, I'm very sorry for any inconveniences this might have caused. The project can be assigned to someone else while I will still attempt making the design, and if I can, I push it, thanks.

**Comment by maddypie** [comment]
Hello @precious-omovoiye, happy holidays :snowman_with_snow:  and I hope you are doing well. I'm excited to say PyCalc is under *v2.0-alpha* revision :partying_face: . We now have a tab-style for **mode BASIC** and **mode ADVANCED** (refer #11). I believe this would a perfect time from some new theme, design and layout changes.
I know you are busy, but if you could cook up some colour-schemes or design layout, I could implement those in the code. Thanks in advance.
Cheers!!

**Comment by mohitdmak** [comment]
Can I work on this issue?

**Comment by precious-omovoiye** [comment]
Sorry for the late reply @maddypie, I'm just seeing this now, I would work on it.

**Comment by maddypie** [comment]
@mohitdmak, Yes you can also work on this issue. @precious-omovoiye is already working on this but more the themes/styles/layouts we have the better. So, do get involved in this and you can always post your queries here. 
Let me know if you are ready to work on this.

**Comment by mohitdmak** [comment]
Oh np I will start work, but I am still a beginner so it might take me some time to understand and implement the task .

**Comment by mohitdmak** [comment]
@maddypie @precious-omovoiye  I am new to pure python apps without any frameworks actually, can you pls tell how do I run it to check my changes in code?

**Comment by precious-omovoiye** [comment]
@mohitdmak are you implementing the design already?

**Comment by mohitdmak** [comment]
no i havent made the changes already but I want to see how the calc is working currently
shud i download Xming for it?

**Comment by mohitdmak** [comment]
Hey I am now able to run it..actually earlier I was trying to run it from my wsl linux shell, but it did not have gui support , so now it works from my windows powershell
@precious-omovoiye @maddypie

**Comment by maddypie** [comment]
@mohitdmak After you have cloned this repository, I recommend you to create a virtual environment. Pip install the requirements.txt. Additionally, if you are running Linux, you will have to ```sudo apt install xclip```. You can now start the program from the terminal by calling *main.py*.

```
# activate virtual-environment
git clone https://github.com/maddypie/PyCalc.git
sudo apt install xclip
cd ./PyCalc
pip install -r requirements.txt
python main.py
```

**Comment by maddypie** [comment]
@precious-omovoiye, These are the available colors in Tkinter GUI library:
![TkInterColorCharts](https://user-images.githubusercontent.com/66778010/103112904-237ab500-467e-11eb-9f63-7f19d94d8c43.png)

**Comment by mohitdmak** [comment]
> @mohitdmak After you have cloned this repository, I recommend you to create a virtual environment. Pip install the requirements.txt. Additionally, if you are running Linux, you will have to `sudo apt install xclip`. You can now start the program from the terminal by calling _main.py_.
> 
> ```
> # activate virtual-environment
> git clone https://github.com/maddypie/PyCalc.git
> sudo apt install xclip
> cd ./PyCalc
> pip install -r requirements.txt
> python main.py
> ```

@maddypie , I have already done this, working fine, thanks,:) I have also made a theme but the pull request got cancelled because I think the flak8 linting had a problem with too many words in a single line of code. I will send the screenshot of the theme and maybe make a few better themes too.But my college exams are approaching actually, can I correspond to you in a few weeks?

**Comment by maddypie** [comment]
> But my college exams are approaching actually, can I correspond to you in a few weeks?

No worries. Take it easy :smile:

**Comment by precious-omovoiye** [comment]
> @precious-omovoiye, These are the available colors in Tkinter GUI library:
> ![TkInterColorCharts](https://user-images.githubusercontent.com/66778010/103112904-237ab500-467e-11eb-9f63-7f19d94d8c43.png)

Noted

**Comment by maddypie** [comment]
@precious-omovoiye Are you working on this?

**Comment by precious-omovoiye** [comment]
Yes @maddypie, this is the link to the figma file https://www.figma.com/file/HU5QIsbGT5oJQcHeKRfoqN/Pymanujan-UI-Design?node-id=0%3A1
You can click on the link to view it and make your observations, I'm still working on it though, for now only the basic view is ready

**Comment by maddypie** [comment]
> Yes @maddypie, this is the link to the figma file https://www.figma.com/file/HU5QIsbGT5oJQcHeKRfoqN/Pymanujan-UI-Design?node-id=0%3A1
> You can click on the link to view it and make your observations, I'm still working on it though, for now only the basic view is ready

@precious-omovoiye This is coming out really good. UI looks pleasant to the eyes and I am really impressed. Here is the first implementation on Pymanujan UI:

![Pymanujan_test-1](https://user-images.githubusercontent.com/66778010/103730910-f0cfa580-5009-11eb-9f9b-fb702f3bb76b.png)

I am still trying to match the display width with your design. Please continue with Advanced mode. 
Thank you so much :smile:

**Comment by precious-omovoiye** [comment]
Alright @maddypie, I used Google Pixel 2 XL screen size for the design.

**Comment by tsadarsh** [comment]
Thanks @precious-omovoiye. UI is updated and it looks awesome.
Cheers!
